{
 "title": "Docker资源监控看板",
 "description": "cadvisor:v0.32.0",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "项目",
    "query": "label_values(container_last_seen, project)"
   },
   {
    "name": "server",
    "label": "主机",
    "query": "label_values(container_last_seen{project=~\"$project\"}, server)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(container_last_seen{project=~\"$project\",server=~\"$server\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{project=~\"$project\",instance=~\"$instance\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{project=~\"$project\",instance=~\"$instance\",image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{project=~\"$project\",instance=~\"$instance\",image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_user_seconds_total{project=~\"$project\",instance=~\"$instance\",image!=\"\"}[1m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "当前常驻内存使用量 - container_memory_rss （docker stats统计展示的即此内存）",
   "type": "graph",
   "description": "RSS内存，即常驻内存集（Resident Set Size），是分配给进程使用实际物理内存，而不是磁盘上缓存的虚拟内存。RSS内存包括所有分配的栈内存和堆内存，以及加载到物理内存中的共享库占用的内存空间，但不包括进入交换分区的内存。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{project=~\"$project\",instance=~\"$instance\",image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "当前内存使用量 - container_memory_usage_bytes （已经申请的内存+工作集使用的内存）",
   "type": "graph",
   "description": "当前使用的内存量，包括所有的使用内存，不管有没有被访问（container_memory_usage_bytes）",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{project=~\"$project\",instance=~\"$instance\",image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "当前内存工作集使用量 - container_memory_working_set_bytes",
   "type": "graph",
   "description": "当前内存工作集（working set）使用量。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{project=~\"$project\",instance=~\"$instance\",image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{project=~\"$project\",instance=~\"$instance\",image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{project=~\"$project\",instance=~\"$instance\",image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{project=~\"$project\",instance=~\"$instance\",image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{project=~\"$project\",instance=~\"$instance\",image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}