{
 "title": "NVIDIA GPU 资源监控看板",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "tags": [
  "Prometheus",
  "GPU"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "DCGM实例",
    "query": "label_values(DCGM_FI_DEV_FB_USED, instance)"
   },
   { "name": "gpu", "label": "GPU序号", "query": "label_values(gpu)" }
  ]
 },
 "panels": [
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "GPU利用率 ",
   "type": "graph",
   "description": "GPU Utilization",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "GPU内存利用率",
   "type": "graph",
   "description": " GPU Mem Cpy Utilization",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{instance=~\"$instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_CLOCK{instance=~\"$instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"$instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}